//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./HardwareService_types');
//HELPER FUNCTIONS AND STRUCTURES

HardwareService_configure_args = function(args) {
  this.jsonDocumentText = null;
  if (args) {
    if (args.jsonDocumentText !== undefined) {
      this.jsonDocumentText = args.jsonDocumentText;
    }
  }
};
HardwareService_configure_args.prototype = {};
HardwareService_configure_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.jsonDocumentText = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HardwareService_configure_args.prototype.write = function(output) {
  output.writeStructBegin('HardwareService_configure_args');
  if (this.jsonDocumentText !== null && this.jsonDocumentText !== undefined) {
    output.writeFieldBegin('jsonDocumentText', Thrift.Type.STRING, 1);
    output.writeString(this.jsonDocumentText);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HardwareService_configure_result = function(args) {
  this.ouch = null;
  if (args instanceof ttypes.InvalidOperation) {
    this.ouch = args;
    return;
  }
  if (args) {
    if (args.ouch !== undefined) {
      this.ouch = args.ouch;
    }
  }
};
HardwareService_configure_result.prototype = {};
HardwareService_configure_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ouch = new ttypes.InvalidOperation();
        this.ouch.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HardwareService_configure_result.prototype.write = function(output) {
  output.writeStructBegin('HardwareService_configure_result');
  if (this.ouch !== null && this.ouch !== undefined) {
    output.writeFieldBegin('ouch', Thrift.Type.STRUCT, 1);
    this.ouch.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HardwareService_pour_args = function(args) {
  this.from = null;
  this.to = null;
  if (args) {
    if (args.from !== undefined) {
      this.from = args.from;
    }
    if (args.to !== undefined) {
      this.to = args.to;
    }
  }
};
HardwareService_pour_args.prototype = {};
HardwareService_pour_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.from = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.to = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HardwareService_pour_args.prototype.write = function(output) {
  output.writeStructBegin('HardwareService_pour_args');
  if (this.from !== null && this.from !== undefined) {
    output.writeFieldBegin('from', Thrift.Type.I32, 1);
    output.writeI32(this.from);
    output.writeFieldEnd();
  }
  if (this.to !== null && this.to !== undefined) {
    output.writeFieldBegin('to', Thrift.Type.I32, 2);
    output.writeI32(this.to);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HardwareService_pour_result = function(args) {
  this.ouch = null;
  if (args instanceof ttypes.InvalidOperation) {
    this.ouch = args;
    return;
  }
  if (args) {
    if (args.ouch !== undefined) {
      this.ouch = args.ouch;
    }
  }
};
HardwareService_pour_result.prototype = {};
HardwareService_pour_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ouch = new ttypes.InvalidOperation();
        this.ouch.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HardwareService_pour_result.prototype.write = function(output) {
  output.writeStructBegin('HardwareService_pour_result');
  if (this.ouch !== null && this.ouch !== undefined) {
    output.writeFieldBegin('ouch', Thrift.Type.STRUCT, 1);
    this.ouch.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HardwareService_getInput_args = function(args) {
};
HardwareService_getInput_args.prototype = {};
HardwareService_getInput_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HardwareService_getInput_args.prototype.write = function(output) {
  output.writeStructBegin('HardwareService_getInput_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HardwareService_getInput_result = function(args) {
  this.success = null;
  this.ouch = null;
  if (args instanceof ttypes.InvalidOperation) {
    this.ouch = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.ouch !== undefined) {
      this.ouch = args.ouch;
    }
  }
};
HardwareService_getInput_result.prototype = {};
HardwareService_getInput_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.HardwareInput();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ouch = new ttypes.InvalidOperation();
        this.ouch.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HardwareService_getInput_result.prototype.write = function(output) {
  output.writeStructBegin('HardwareService_getInput_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.ouch !== null && this.ouch !== undefined) {
    output.writeFieldBegin('ouch', Thrift.Type.STRUCT, 1);
    this.ouch.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HardwareService_startPump_args = function(args) {
  this.pumpId = null;
  if (args) {
    if (args.pumpId !== undefined) {
      this.pumpId = args.pumpId;
    }
  }
};
HardwareService_startPump_args.prototype = {};
HardwareService_startPump_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.pumpId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HardwareService_startPump_args.prototype.write = function(output) {
  output.writeStructBegin('HardwareService_startPump_args');
  if (this.pumpId !== null && this.pumpId !== undefined) {
    output.writeFieldBegin('pumpId', Thrift.Type.I32, 1);
    output.writeI32(this.pumpId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HardwareService_startPump_result = function(args) {
  this.ouch = null;
  if (args instanceof ttypes.InvalidOperation) {
    this.ouch = args;
    return;
  }
  if (args) {
    if (args.ouch !== undefined) {
      this.ouch = args.ouch;
    }
  }
};
HardwareService_startPump_result.prototype = {};
HardwareService_startPump_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ouch = new ttypes.InvalidOperation();
        this.ouch.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HardwareService_startPump_result.prototype.write = function(output) {
  output.writeStructBegin('HardwareService_startPump_result');
  if (this.ouch !== null && this.ouch !== undefined) {
    output.writeFieldBegin('ouch', Thrift.Type.STRUCT, 1);
    this.ouch.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HardwareService_stopPump_args = function(args) {
  this.pumpId = null;
  if (args) {
    if (args.pumpId !== undefined) {
      this.pumpId = args.pumpId;
    }
  }
};
HardwareService_stopPump_args.prototype = {};
HardwareService_stopPump_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.pumpId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HardwareService_stopPump_args.prototype.write = function(output) {
  output.writeStructBegin('HardwareService_stopPump_args');
  if (this.pumpId !== null && this.pumpId !== undefined) {
    output.writeFieldBegin('pumpId', Thrift.Type.I32, 1);
    output.writeI32(this.pumpId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HardwareService_stopPump_result = function(args) {
  this.success = null;
  this.ouch = null;
  if (args instanceof ttypes.InvalidOperation) {
    this.ouch = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.ouch !== undefined) {
      this.ouch = args.ouch;
    }
  }
};
HardwareService_stopPump_result.prototype = {};
HardwareService_stopPump_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.StopPumpResult();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ouch = new ttypes.InvalidOperation();
        this.ouch.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HardwareService_stopPump_result.prototype.write = function(output) {
  output.writeStructBegin('HardwareService_stopPump_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.ouch !== null && this.ouch !== undefined) {
    output.writeFieldBegin('ouch', Thrift.Type.STRUCT, 1);
    this.ouch.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HardwareService_getServiceStatus_args = function(args) {
};
HardwareService_getServiceStatus_args.prototype = {};
HardwareService_getServiceStatus_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HardwareService_getServiceStatus_args.prototype.write = function(output) {
  output.writeStructBegin('HardwareService_getServiceStatus_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HardwareService_getServiceStatus_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
HardwareService_getServiceStatus_result.prototype = {};
HardwareService_getServiceStatus_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.ServiceStatus();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HardwareService_getServiceStatus_result.prototype.write = function(output) {
  output.writeStructBegin('HardwareService_getServiceStatus_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HardwareService_GetServiceStateJson_args = function(args) {
};
HardwareService_GetServiceStateJson_args.prototype = {};
HardwareService_GetServiceStateJson_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HardwareService_GetServiceStateJson_args.prototype.write = function(output) {
  output.writeStructBegin('HardwareService_GetServiceStateJson_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HardwareService_GetServiceStateJson_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
HardwareService_GetServiceStateJson_result.prototype = {};
HardwareService_GetServiceStateJson_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HardwareService_GetServiceStateJson_result.prototype.write = function(output) {
  output.writeStructBegin('HardwareService_GetServiceStateJson_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HardwareService_ping_args = function(args) {
  this.arg = null;
  if (args) {
    if (args.arg !== undefined) {
      this.arg = args.arg;
    }
  }
};
HardwareService_ping_args.prototype = {};
HardwareService_ping_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.arg = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HardwareService_ping_args.prototype.write = function(output) {
  output.writeStructBegin('HardwareService_ping_args');
  if (this.arg !== null && this.arg !== undefined) {
    output.writeFieldBegin('arg', Thrift.Type.I32, 1);
    output.writeI32(this.arg);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HardwareService_ping_result = function(args) {
};
HardwareService_ping_result.prototype = {};
HardwareService_ping_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HardwareService_ping_result.prototype.write = function(output) {
  output.writeStructBegin('HardwareService_ping_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HardwareServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
HardwareServiceClient.prototype = {};
HardwareServiceClient.prototype.seqid = function() { return this._seqid; }
HardwareServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
HardwareServiceClient.prototype.configure = function(jsonDocumentText, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_configure(jsonDocumentText);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_configure(jsonDocumentText);
  }
};

HardwareServiceClient.prototype.send_configure = function(jsonDocumentText) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('configure', Thrift.MessageType.CALL, this.seqid());
  var args = new HardwareService_configure_args();
  args.jsonDocumentText = jsonDocumentText;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

HardwareServiceClient.prototype.recv_configure = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new HardwareService_configure_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ouch) {
    return callback(result.ouch);
  }
  callback(null)
};
HardwareServiceClient.prototype.pour = function(from, to, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_pour(from, to);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_pour(from, to);
  }
};

HardwareServiceClient.prototype.send_pour = function(from, to) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('pour', Thrift.MessageType.CALL, this.seqid());
  var args = new HardwareService_pour_args();
  args.from = from;
  args.to = to;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

HardwareServiceClient.prototype.recv_pour = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new HardwareService_pour_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ouch) {
    return callback(result.ouch);
  }
  callback(null)
};
HardwareServiceClient.prototype.getInput = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getInput();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getInput();
  }
};

HardwareServiceClient.prototype.send_getInput = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getInput', Thrift.MessageType.CALL, this.seqid());
  var args = new HardwareService_getInput_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

HardwareServiceClient.prototype.recv_getInput = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new HardwareService_getInput_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ouch) {
    return callback(result.ouch);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getInput failed: unknown result');
};
HardwareServiceClient.prototype.startPump = function(pumpId, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_startPump(pumpId);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_startPump(pumpId);
  }
};

HardwareServiceClient.prototype.send_startPump = function(pumpId) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('startPump', Thrift.MessageType.CALL, this.seqid());
  var args = new HardwareService_startPump_args();
  args.pumpId = pumpId;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

HardwareServiceClient.prototype.recv_startPump = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new HardwareService_startPump_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ouch) {
    return callback(result.ouch);
  }
  callback(null)
};
HardwareServiceClient.prototype.stopPump = function(pumpId, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_stopPump(pumpId);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_stopPump(pumpId);
  }
};

HardwareServiceClient.prototype.send_stopPump = function(pumpId) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('stopPump', Thrift.MessageType.CALL, this.seqid());
  var args = new HardwareService_stopPump_args();
  args.pumpId = pumpId;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

HardwareServiceClient.prototype.recv_stopPump = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new HardwareService_stopPump_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ouch) {
    return callback(result.ouch);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('stopPump failed: unknown result');
};
HardwareServiceClient.prototype.getServiceStatus = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getServiceStatus();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getServiceStatus();
  }
};

HardwareServiceClient.prototype.send_getServiceStatus = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getServiceStatus', Thrift.MessageType.CALL, this.seqid());
  var args = new HardwareService_getServiceStatus_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

HardwareServiceClient.prototype.recv_getServiceStatus = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new HardwareService_getServiceStatus_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getServiceStatus failed: unknown result');
};
HardwareServiceClient.prototype.GetServiceStateJson = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_GetServiceStateJson();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_GetServiceStateJson();
  }
};

HardwareServiceClient.prototype.send_GetServiceStateJson = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('GetServiceStateJson', Thrift.MessageType.CALL, this.seqid());
  var args = new HardwareService_GetServiceStateJson_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

HardwareServiceClient.prototype.recv_GetServiceStateJson = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new HardwareService_GetServiceStateJson_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('GetServiceStateJson failed: unknown result');
};
HardwareServiceClient.prototype.ping = function(arg, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_ping(arg);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_ping(arg);
  }
};

HardwareServiceClient.prototype.send_ping = function(arg) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('ping', Thrift.MessageType.CALL, this.seqid());
  var args = new HardwareService_ping_args();
  args.arg = arg;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

HardwareServiceClient.prototype.recv_ping = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new HardwareService_ping_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
HardwareServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
HardwareServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

HardwareServiceProcessor.prototype.process_configure = function(seqid, input, output) {
  var args = new HardwareService_configure_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.configure.length === 1) {
    Q.fcall(this._handler.configure, args.jsonDocumentText)
      .then(function(result) {
        var result = new HardwareService_configure_result({success: result});
        output.writeMessageBegin("configure", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new HardwareService_configure_result(err);
        output.writeMessageBegin("configure", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.configure(args.jsonDocumentText,  function (err, result) {
      var result = new HardwareService_configure_result((err != null ? err : {success: result}));
      output.writeMessageBegin("configure", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

HardwareServiceProcessor.prototype.process_pour = function(seqid, input, output) {
  var args = new HardwareService_pour_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.pour.length === 2) {
    Q.fcall(this._handler.pour, args.from, args.to)
      .then(function(result) {
        var result = new HardwareService_pour_result({success: result});
        output.writeMessageBegin("pour", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new HardwareService_pour_result(err);
        output.writeMessageBegin("pour", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.pour(args.from, args.to,  function (err, result) {
      var result = new HardwareService_pour_result((err != null ? err : {success: result}));
      output.writeMessageBegin("pour", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

HardwareServiceProcessor.prototype.process_getInput = function(seqid, input, output) {
  var args = new HardwareService_getInput_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getInput.length === 0) {
    Q.fcall(this._handler.getInput)
      .then(function(result) {
        var result = new HardwareService_getInput_result({success: result});
        output.writeMessageBegin("getInput", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new HardwareService_getInput_result(err);
        output.writeMessageBegin("getInput", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getInput( function (err, result) {
      var result = new HardwareService_getInput_result((err != null ? err : {success: result}));
      output.writeMessageBegin("getInput", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

HardwareServiceProcessor.prototype.process_startPump = function(seqid, input, output) {
  var args = new HardwareService_startPump_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.startPump.length === 1) {
    Q.fcall(this._handler.startPump, args.pumpId)
      .then(function(result) {
        var result = new HardwareService_startPump_result({success: result});
        output.writeMessageBegin("startPump", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new HardwareService_startPump_result(err);
        output.writeMessageBegin("startPump", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.startPump(args.pumpId,  function (err, result) {
      var result = new HardwareService_startPump_result((err != null ? err : {success: result}));
      output.writeMessageBegin("startPump", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

HardwareServiceProcessor.prototype.process_stopPump = function(seqid, input, output) {
  var args = new HardwareService_stopPump_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.stopPump.length === 1) {
    Q.fcall(this._handler.stopPump, args.pumpId)
      .then(function(result) {
        var result = new HardwareService_stopPump_result({success: result});
        output.writeMessageBegin("stopPump", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new HardwareService_stopPump_result(err);
        output.writeMessageBegin("stopPump", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.stopPump(args.pumpId,  function (err, result) {
      var result = new HardwareService_stopPump_result((err != null ? err : {success: result}));
      output.writeMessageBegin("stopPump", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

HardwareServiceProcessor.prototype.process_getServiceStatus = function(seqid, input, output) {
  var args = new HardwareService_getServiceStatus_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getServiceStatus.length === 0) {
    Q.fcall(this._handler.getServiceStatus)
      .then(function(result) {
        var result = new HardwareService_getServiceStatus_result({success: result});
        output.writeMessageBegin("getServiceStatus", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new HardwareService_getServiceStatus_result(err);
        output.writeMessageBegin("getServiceStatus", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getServiceStatus( function (err, result) {
      var result = new HardwareService_getServiceStatus_result((err != null ? err : {success: result}));
      output.writeMessageBegin("getServiceStatus", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

HardwareServiceProcessor.prototype.process_GetServiceStateJson = function(seqid, input, output) {
  var args = new HardwareService_GetServiceStateJson_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.GetServiceStateJson.length === 0) {
    Q.fcall(this._handler.GetServiceStateJson)
      .then(function(result) {
        var result = new HardwareService_GetServiceStateJson_result({success: result});
        output.writeMessageBegin("GetServiceStateJson", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new HardwareService_GetServiceStateJson_result(err);
        output.writeMessageBegin("GetServiceStateJson", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.GetServiceStateJson( function (err, result) {
      var result = new HardwareService_GetServiceStateJson_result((err != null ? err : {success: result}));
      output.writeMessageBegin("GetServiceStateJson", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

HardwareServiceProcessor.prototype.process_ping = function(seqid, input, output) {
  var args = new HardwareService_ping_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.ping.length === 1) {
    Q.fcall(this._handler.ping, args.arg)
      .then(function(result) {
        var result = new HardwareService_ping_result({success: result});
        output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new HardwareService_ping_result(err);
        output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.ping(args.arg,  function (err, result) {
      var result = new HardwareService_ping_result((err != null ? err : {success: result}));
      output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

