//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./WateringService_types');
//HELPER FUNCTIONS AND STRUCTURES

WateringService_configure_args = function(args) {
  this.configuration = null;
  if (args) {
    if (args.configuration !== undefined) {
      this.configuration = args.configuration;
    }
  }
};
WateringService_configure_args.prototype = {};
WateringService_configure_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.configuration = new ttypes.Configuration();
        this.configuration.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

WateringService_configure_args.prototype.write = function(output) {
  output.writeStructBegin('WateringService_configure_args');
  if (this.configuration !== null && this.configuration !== undefined) {
    output.writeFieldBegin('configuration', Thrift.Type.STRUCT, 1);
    this.configuration.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

WateringService_configure_result = function(args) {
  this.ouch = null;
  if (args instanceof ttypes.InvalidOperation) {
    this.ouch = args;
    return;
  }
  if (args) {
    if (args.ouch !== undefined) {
      this.ouch = args.ouch;
    }
  }
};
WateringService_configure_result.prototype = {};
WateringService_configure_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ouch = new ttypes.InvalidOperation();
        this.ouch.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

WateringService_configure_result.prototype.write = function(output) {
  output.writeStructBegin('WateringService_configure_result');
  if (this.ouch !== null && this.ouch !== undefined) {
    output.writeFieldBegin('ouch', Thrift.Type.STRUCT, 1);
    this.ouch.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

WateringService_pour_args = function(args) {
  this.from = null;
  this.to = null;
  if (args) {
    if (args.from !== undefined) {
      this.from = args.from;
    }
    if (args.to !== undefined) {
      this.to = args.to;
    }
  }
};
WateringService_pour_args.prototype = {};
WateringService_pour_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.from = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.to = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

WateringService_pour_args.prototype.write = function(output) {
  output.writeStructBegin('WateringService_pour_args');
  if (this.from !== null && this.from !== undefined) {
    output.writeFieldBegin('from', Thrift.Type.I32, 1);
    output.writeI32(this.from);
    output.writeFieldEnd();
  }
  if (this.to !== null && this.to !== undefined) {
    output.writeFieldBegin('to', Thrift.Type.I32, 2);
    output.writeI32(this.to);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

WateringService_pour_result = function(args) {
  this.ouch = null;
  if (args instanceof ttypes.InvalidOperation) {
    this.ouch = args;
    return;
  }
  if (args) {
    if (args.ouch !== undefined) {
      this.ouch = args.ouch;
    }
  }
};
WateringService_pour_result.prototype = {};
WateringService_pour_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ouch = new ttypes.InvalidOperation();
        this.ouch.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

WateringService_pour_result.prototype.write = function(output) {
  output.writeStructBegin('WateringService_pour_result');
  if (this.ouch !== null && this.ouch !== undefined) {
    output.writeFieldBegin('ouch', Thrift.Type.STRUCT, 1);
    this.ouch.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

WateringService_getInput_args = function(args) {
};
WateringService_getInput_args.prototype = {};
WateringService_getInput_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

WateringService_getInput_args.prototype.write = function(output) {
  output.writeStructBegin('WateringService_getInput_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

WateringService_getInput_result = function(args) {
  this.success = null;
  this.ouch = null;
  if (args instanceof ttypes.InvalidOperation) {
    this.ouch = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.ouch !== undefined) {
      this.ouch = args.ouch;
    }
  }
};
WateringService_getInput_result.prototype = {};
WateringService_getInput_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.HardwareInput();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ouch = new ttypes.InvalidOperation();
        this.ouch.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

WateringService_getInput_result.prototype.write = function(output) {
  output.writeStructBegin('WateringService_getInput_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.ouch !== null && this.ouch !== undefined) {
    output.writeFieldBegin('ouch', Thrift.Type.STRUCT, 1);
    this.ouch.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

WateringService_startPump_args = function(args) {
  this.pumpId = null;
  if (args) {
    if (args.pumpId !== undefined) {
      this.pumpId = args.pumpId;
    }
  }
};
WateringService_startPump_args.prototype = {};
WateringService_startPump_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.pumpId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

WateringService_startPump_args.prototype.write = function(output) {
  output.writeStructBegin('WateringService_startPump_args');
  if (this.pumpId !== null && this.pumpId !== undefined) {
    output.writeFieldBegin('pumpId', Thrift.Type.I32, 1);
    output.writeI32(this.pumpId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

WateringService_startPump_result = function(args) {
  this.ouch = null;
  if (args instanceof ttypes.InvalidOperation) {
    this.ouch = args;
    return;
  }
  if (args) {
    if (args.ouch !== undefined) {
      this.ouch = args.ouch;
    }
  }
};
WateringService_startPump_result.prototype = {};
WateringService_startPump_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ouch = new ttypes.InvalidOperation();
        this.ouch.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

WateringService_startPump_result.prototype.write = function(output) {
  output.writeStructBegin('WateringService_startPump_result');
  if (this.ouch !== null && this.ouch !== undefined) {
    output.writeFieldBegin('ouch', Thrift.Type.STRUCT, 1);
    this.ouch.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

WateringService_stopPump_args = function(args) {
  this.pumpId = null;
  if (args) {
    if (args.pumpId !== undefined) {
      this.pumpId = args.pumpId;
    }
  }
};
WateringService_stopPump_args.prototype = {};
WateringService_stopPump_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.pumpId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

WateringService_stopPump_args.prototype.write = function(output) {
  output.writeStructBegin('WateringService_stopPump_args');
  if (this.pumpId !== null && this.pumpId !== undefined) {
    output.writeFieldBegin('pumpId', Thrift.Type.I32, 1);
    output.writeI32(this.pumpId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

WateringService_stopPump_result = function(args) {
  this.success = null;
  this.ouch = null;
  if (args instanceof ttypes.InvalidOperation) {
    this.ouch = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.ouch !== undefined) {
      this.ouch = args.ouch;
    }
  }
};
WateringService_stopPump_result.prototype = {};
WateringService_stopPump_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.StopPumpResult();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ouch = new ttypes.InvalidOperation();
        this.ouch.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

WateringService_stopPump_result.prototype.write = function(output) {
  output.writeStructBegin('WateringService_stopPump_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.ouch !== null && this.ouch !== undefined) {
    output.writeFieldBegin('ouch', Thrift.Type.STRUCT, 1);
    this.ouch.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

WateringServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
WateringServiceClient.prototype = {};
WateringServiceClient.prototype.seqid = function() { return this._seqid; }
WateringServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
WateringServiceClient.prototype.configure = function(configuration, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_configure(configuration);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_configure(configuration);
  }
};

WateringServiceClient.prototype.send_configure = function(configuration) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('configure', Thrift.MessageType.CALL, this.seqid());
  var args = new WateringService_configure_args();
  args.configuration = configuration;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

WateringServiceClient.prototype.recv_configure = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new WateringService_configure_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ouch) {
    return callback(result.ouch);
  }
  callback(null)
};
WateringServiceClient.prototype.pour = function(from, to, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_pour(from, to);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_pour(from, to);
  }
};

WateringServiceClient.prototype.send_pour = function(from, to) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('pour', Thrift.MessageType.CALL, this.seqid());
  var args = new WateringService_pour_args();
  args.from = from;
  args.to = to;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

WateringServiceClient.prototype.recv_pour = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new WateringService_pour_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ouch) {
    return callback(result.ouch);
  }
  callback(null)
};
WateringServiceClient.prototype.getInput = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getInput();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getInput();
  }
};

WateringServiceClient.prototype.send_getInput = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getInput', Thrift.MessageType.CALL, this.seqid());
  var args = new WateringService_getInput_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

WateringServiceClient.prototype.recv_getInput = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new WateringService_getInput_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ouch) {
    return callback(result.ouch);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getInput failed: unknown result');
};
WateringServiceClient.prototype.startPump = function(pumpId, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_startPump(pumpId);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_startPump(pumpId);
  }
};

WateringServiceClient.prototype.send_startPump = function(pumpId) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('startPump', Thrift.MessageType.CALL, this.seqid());
  var args = new WateringService_startPump_args();
  args.pumpId = pumpId;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

WateringServiceClient.prototype.recv_startPump = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new WateringService_startPump_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ouch) {
    return callback(result.ouch);
  }
  callback(null)
};
WateringServiceClient.prototype.stopPump = function(pumpId, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_stopPump(pumpId);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_stopPump(pumpId);
  }
};

WateringServiceClient.prototype.send_stopPump = function(pumpId) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('stopPump', Thrift.MessageType.CALL, this.seqid());
  var args = new WateringService_stopPump_args();
  args.pumpId = pumpId;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

WateringServiceClient.prototype.recv_stopPump = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new WateringService_stopPump_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ouch) {
    return callback(result.ouch);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('stopPump failed: unknown result');
};
WateringServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
WateringServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

WateringServiceProcessor.prototype.process_configure = function(seqid, input, output) {
  var args = new WateringService_configure_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.configure.length === 1) {
    Q.fcall(this._handler.configure, args.configuration)
      .then(function(result) {
        var result = new WateringService_configure_result({success: result});
        output.writeMessageBegin("configure", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new WateringService_configure_result(err);
        output.writeMessageBegin("configure", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.configure(args.configuration,  function (err, result) {
      var result = new WateringService_configure_result((err != null ? err : {success: result}));
      output.writeMessageBegin("configure", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

WateringServiceProcessor.prototype.process_pour = function(seqid, input, output) {
  var args = new WateringService_pour_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.pour.length === 2) {
    Q.fcall(this._handler.pour, args.from, args.to)
      .then(function(result) {
        var result = new WateringService_pour_result({success: result});
        output.writeMessageBegin("pour", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new WateringService_pour_result(err);
        output.writeMessageBegin("pour", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.pour(args.from, args.to,  function (err, result) {
      var result = new WateringService_pour_result((err != null ? err : {success: result}));
      output.writeMessageBegin("pour", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

WateringServiceProcessor.prototype.process_getInput = function(seqid, input, output) {
  var args = new WateringService_getInput_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getInput.length === 0) {
    Q.fcall(this._handler.getInput)
      .then(function(result) {
        var result = new WateringService_getInput_result({success: result});
        output.writeMessageBegin("getInput", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new WateringService_getInput_result(err);
        output.writeMessageBegin("getInput", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getInput( function (err, result) {
      var result = new WateringService_getInput_result((err != null ? err : {success: result}));
      output.writeMessageBegin("getInput", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

WateringServiceProcessor.prototype.process_startPump = function(seqid, input, output) {
  var args = new WateringService_startPump_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.startPump.length === 1) {
    Q.fcall(this._handler.startPump, args.pumpId)
      .then(function(result) {
        var result = new WateringService_startPump_result({success: result});
        output.writeMessageBegin("startPump", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new WateringService_startPump_result(err);
        output.writeMessageBegin("startPump", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.startPump(args.pumpId,  function (err, result) {
      var result = new WateringService_startPump_result((err != null ? err : {success: result}));
      output.writeMessageBegin("startPump", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

WateringServiceProcessor.prototype.process_stopPump = function(seqid, input, output) {
  var args = new WateringService_stopPump_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.stopPump.length === 1) {
    Q.fcall(this._handler.stopPump, args.pumpId)
      .then(function(result) {
        var result = new WateringService_stopPump_result({success: result});
        output.writeMessageBegin("stopPump", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new WateringService_stopPump_result(err);
        output.writeMessageBegin("stopPump", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.stopPump(args.pumpId,  function (err, result) {
      var result = new WateringService_stopPump_result((err != null ? err : {success: result}));
      output.writeMessageBegin("stopPump", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

