// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "HardwareService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::Tabletochki;

class HardwareServiceHandler : virtual public HardwareServiceIf {
 public:
  HardwareServiceHandler() {
    // Your initialization goes here
  }

  void configure(const Configuration& configuration) {
    // Your implementation goes here
    printf("configure\n");
  }

  void pour(const Container::type from, const Container::type to) {
    // Your implementation goes here
    printf("pour\n");
  }

  void getInput(HardwareInput& _return) {
    // Your implementation goes here
    printf("getInput\n");
  }

  void startPump(const int32_t pumpId) {
    // Your implementation goes here
    printf("startPump\n");
  }

  void stopPump(StopPumpResult& _return, const int32_t pumpId) {
    // Your implementation goes here
    printf("stopPump\n");
  }

  void getServiceStatus(ServiceStatus& _return) {
    // Your implementation goes here
    printf("getServiceStatus\n");
  }

  void ping(const int32_t arg) {
    // Your implementation goes here
    printf("ping\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<HardwareServiceHandler> handler(new HardwareServiceHandler());
  shared_ptr<TProcessor> processor(new HardwareServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

