/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "HardwareService_constants.h"

namespace Tabletochki {

const HardwareServiceConstants g_HardwareService_constants;

HardwareServiceConstants::HardwareServiceConstants() {
}

} // namespace

