/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef HardwareService_CONSTANTS_H
#define HardwareService_CONSTANTS_H

#include "HardwareService_types.h"

namespace Tabletochki {

class HardwareServiceConstants {
 public:
  HardwareServiceConstants();

};

extern const HardwareServiceConstants g_HardwareService_constants;

} // namespace

#endif
