// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "HardwareService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::Tabletochki;

class HardwareServiceHandler : virtual public HardwareServiceIf {
 public:
  HardwareServiceHandler() {
    // Your initialization goes here
  }

  void applyConfiguration(const std::string& jsonDocumentText) {
    // Your implementation goes here
    printf("applyConfiguration\n");
  }

  void startPump(const PumpIdentifier::type pumpId) {
    // Your implementation goes here
    printf("startPump\n");
  }

  void stopPump(StopPumpResult& _return, const PumpIdentifier::type pumpId) {
    // Your implementation goes here
    printf("stopPump\n");
  }

  void getServiceStatus(ServiceStatus& _return) {
    // Your implementation goes here
    printf("getServiceStatus\n");
  }

  void getServiceStateJson(std::string& _return) {
    // Your implementation goes here
    printf("getServiceStateJson\n");
  }

  void fillVisibleContainerMillilitres(const int32_t amount) {
    // Your implementation goes here
    printf("fillVisibleContainerMillilitres\n");
  }

  void emptyVisiableContainerMillilitres(const int32_t amount) {
    // Your implementation goes here
    printf("emptyVisiableContainerMillilitres\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<HardwareServiceHandler> handler(new HardwareServiceHandler());
  shared_ptr<TProcessor> processor(new HardwareServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

