/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef WateringService_H
#define WateringService_H

#include <thrift/TDispatchProcessor.h>
#include "WateringService_types.h"

namespace Tabletochki {

class WateringServiceIf {
 public:
  virtual ~WateringServiceIf() {}
  virtual void configure(const Configuration& configuration) = 0;
  virtual void pour(const Container::type from, const Container::type to) = 0;
  virtual void getInput(HardwareInput& _return) = 0;
  virtual void startPump(const int32_t pumpId) = 0;
  virtual void stopPump(StopPumpResult& _return, const int32_t pumpId) = 0;
};

class WateringServiceIfFactory {
 public:
  typedef WateringServiceIf Handler;

  virtual ~WateringServiceIfFactory() {}

  virtual WateringServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(WateringServiceIf* /* handler */) = 0;
};

class WateringServiceIfSingletonFactory : virtual public WateringServiceIfFactory {
 public:
  WateringServiceIfSingletonFactory(const boost::shared_ptr<WateringServiceIf>& iface) : iface_(iface) {}
  virtual ~WateringServiceIfSingletonFactory() {}

  virtual WateringServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(WateringServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<WateringServiceIf> iface_;
};

class WateringServiceNull : virtual public WateringServiceIf {
 public:
  virtual ~WateringServiceNull() {}
  void configure(const Configuration& /* configuration */) {
    return;
  }
  void pour(const Container::type /* from */, const Container::type /* to */) {
    return;
  }
  void getInput(HardwareInput& /* _return */) {
    return;
  }
  void startPump(const int32_t /* pumpId */) {
    return;
  }
  void stopPump(StopPumpResult& /* _return */, const int32_t /* pumpId */) {
    return;
  }
};

typedef struct _WateringService_configure_args__isset {
  _WateringService_configure_args__isset() : configuration(false) {}
  bool configuration :1;
} _WateringService_configure_args__isset;

class WateringService_configure_args {
 public:

  static const char* ascii_fingerprint; // = "DDA7E42F29E886B5008057C3BA79BE1B";
  static const uint8_t binary_fingerprint[16]; // = {0xDD,0xA7,0xE4,0x2F,0x29,0xE8,0x86,0xB5,0x00,0x80,0x57,0xC3,0xBA,0x79,0xBE,0x1B};

  WateringService_configure_args(const WateringService_configure_args&);
  WateringService_configure_args& operator=(const WateringService_configure_args&);
  WateringService_configure_args() {
  }

  virtual ~WateringService_configure_args() throw();
  Configuration configuration;

  _WateringService_configure_args__isset __isset;

  void __set_configuration(const Configuration& val);

  bool operator == (const WateringService_configure_args & rhs) const
  {
    if (!(configuration == rhs.configuration))
      return false;
    return true;
  }
  bool operator != (const WateringService_configure_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const WateringService_configure_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const WateringService_configure_args& obj);
};


class WateringService_configure_pargs {
 public:

  static const char* ascii_fingerprint; // = "DDA7E42F29E886B5008057C3BA79BE1B";
  static const uint8_t binary_fingerprint[16]; // = {0xDD,0xA7,0xE4,0x2F,0x29,0xE8,0x86,0xB5,0x00,0x80,0x57,0xC3,0xBA,0x79,0xBE,0x1B};


  virtual ~WateringService_configure_pargs() throw();
  const Configuration* configuration;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const WateringService_configure_pargs& obj);
};

typedef struct _WateringService_configure_result__isset {
  _WateringService_configure_result__isset() : ouch(false) {}
  bool ouch :1;
} _WateringService_configure_result__isset;

class WateringService_configure_result {
 public:

  static const char* ascii_fingerprint; // = "75163450D5D62165E86860A3D30E517A";
  static const uint8_t binary_fingerprint[16]; // = {0x75,0x16,0x34,0x50,0xD5,0xD6,0x21,0x65,0xE8,0x68,0x60,0xA3,0xD3,0x0E,0x51,0x7A};

  WateringService_configure_result(const WateringService_configure_result&);
  WateringService_configure_result& operator=(const WateringService_configure_result&);
  WateringService_configure_result() {
  }

  virtual ~WateringService_configure_result() throw();
  InvalidOperation ouch;

  _WateringService_configure_result__isset __isset;

  void __set_ouch(const InvalidOperation& val);

  bool operator == (const WateringService_configure_result & rhs) const
  {
    if (!(ouch == rhs.ouch))
      return false;
    return true;
  }
  bool operator != (const WateringService_configure_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const WateringService_configure_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const WateringService_configure_result& obj);
};

typedef struct _WateringService_configure_presult__isset {
  _WateringService_configure_presult__isset() : ouch(false) {}
  bool ouch :1;
} _WateringService_configure_presult__isset;

class WateringService_configure_presult {
 public:

  static const char* ascii_fingerprint; // = "75163450D5D62165E86860A3D30E517A";
  static const uint8_t binary_fingerprint[16]; // = {0x75,0x16,0x34,0x50,0xD5,0xD6,0x21,0x65,0xE8,0x68,0x60,0xA3,0xD3,0x0E,0x51,0x7A};


  virtual ~WateringService_configure_presult() throw();
  InvalidOperation ouch;

  _WateringService_configure_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const WateringService_configure_presult& obj);
};

typedef struct _WateringService_pour_args__isset {
  _WateringService_pour_args__isset() : from(false), to(false) {}
  bool from :1;
  bool to :1;
} _WateringService_pour_args__isset;

class WateringService_pour_args {
 public:

  static const char* ascii_fingerprint; // = "69EF77542FBF7A8DD68310C9FF3B44BD";
  static const uint8_t binary_fingerprint[16]; // = {0x69,0xEF,0x77,0x54,0x2F,0xBF,0x7A,0x8D,0xD6,0x83,0x10,0xC9,0xFF,0x3B,0x44,0xBD};

  WateringService_pour_args(const WateringService_pour_args&);
  WateringService_pour_args& operator=(const WateringService_pour_args&);
  WateringService_pour_args() : from((Container::type)0), to((Container::type)0) {
  }

  virtual ~WateringService_pour_args() throw();
  Container::type from;
  Container::type to;

  _WateringService_pour_args__isset __isset;

  void __set_from(const Container::type val);

  void __set_to(const Container::type val);

  bool operator == (const WateringService_pour_args & rhs) const
  {
    if (!(from == rhs.from))
      return false;
    if (!(to == rhs.to))
      return false;
    return true;
  }
  bool operator != (const WateringService_pour_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const WateringService_pour_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const WateringService_pour_args& obj);
};


class WateringService_pour_pargs {
 public:

  static const char* ascii_fingerprint; // = "69EF77542FBF7A8DD68310C9FF3B44BD";
  static const uint8_t binary_fingerprint[16]; // = {0x69,0xEF,0x77,0x54,0x2F,0xBF,0x7A,0x8D,0xD6,0x83,0x10,0xC9,0xFF,0x3B,0x44,0xBD};


  virtual ~WateringService_pour_pargs() throw();
  const Container::type* from;
  const Container::type* to;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const WateringService_pour_pargs& obj);
};

typedef struct _WateringService_pour_result__isset {
  _WateringService_pour_result__isset() : ouch(false) {}
  bool ouch :1;
} _WateringService_pour_result__isset;

class WateringService_pour_result {
 public:

  static const char* ascii_fingerprint; // = "75163450D5D62165E86860A3D30E517A";
  static const uint8_t binary_fingerprint[16]; // = {0x75,0x16,0x34,0x50,0xD5,0xD6,0x21,0x65,0xE8,0x68,0x60,0xA3,0xD3,0x0E,0x51,0x7A};

  WateringService_pour_result(const WateringService_pour_result&);
  WateringService_pour_result& operator=(const WateringService_pour_result&);
  WateringService_pour_result() {
  }

  virtual ~WateringService_pour_result() throw();
  InvalidOperation ouch;

  _WateringService_pour_result__isset __isset;

  void __set_ouch(const InvalidOperation& val);

  bool operator == (const WateringService_pour_result & rhs) const
  {
    if (!(ouch == rhs.ouch))
      return false;
    return true;
  }
  bool operator != (const WateringService_pour_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const WateringService_pour_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const WateringService_pour_result& obj);
};

typedef struct _WateringService_pour_presult__isset {
  _WateringService_pour_presult__isset() : ouch(false) {}
  bool ouch :1;
} _WateringService_pour_presult__isset;

class WateringService_pour_presult {
 public:

  static const char* ascii_fingerprint; // = "75163450D5D62165E86860A3D30E517A";
  static const uint8_t binary_fingerprint[16]; // = {0x75,0x16,0x34,0x50,0xD5,0xD6,0x21,0x65,0xE8,0x68,0x60,0xA3,0xD3,0x0E,0x51,0x7A};


  virtual ~WateringService_pour_presult() throw();
  InvalidOperation ouch;

  _WateringService_pour_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const WateringService_pour_presult& obj);
};


class WateringService_getInput_args {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};

  WateringService_getInput_args(const WateringService_getInput_args&);
  WateringService_getInput_args& operator=(const WateringService_getInput_args&);
  WateringService_getInput_args() {
  }

  virtual ~WateringService_getInput_args() throw();

  bool operator == (const WateringService_getInput_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const WateringService_getInput_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const WateringService_getInput_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const WateringService_getInput_args& obj);
};


class WateringService_getInput_pargs {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};


  virtual ~WateringService_getInput_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const WateringService_getInput_pargs& obj);
};

typedef struct _WateringService_getInput_result__isset {
  _WateringService_getInput_result__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _WateringService_getInput_result__isset;

class WateringService_getInput_result {
 public:

  static const char* ascii_fingerprint; // = "D5AC64616352116A03D8E6BA8250FEF9";
  static const uint8_t binary_fingerprint[16]; // = {0xD5,0xAC,0x64,0x61,0x63,0x52,0x11,0x6A,0x03,0xD8,0xE6,0xBA,0x82,0x50,0xFE,0xF9};

  WateringService_getInput_result(const WateringService_getInput_result&);
  WateringService_getInput_result& operator=(const WateringService_getInput_result&);
  WateringService_getInput_result() {
  }

  virtual ~WateringService_getInput_result() throw();
  HardwareInput success;
  InvalidOperation ouch;

  _WateringService_getInput_result__isset __isset;

  void __set_success(const HardwareInput& val);

  void __set_ouch(const InvalidOperation& val);

  bool operator == (const WateringService_getInput_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ouch == rhs.ouch))
      return false;
    return true;
  }
  bool operator != (const WateringService_getInput_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const WateringService_getInput_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const WateringService_getInput_result& obj);
};

typedef struct _WateringService_getInput_presult__isset {
  _WateringService_getInput_presult__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _WateringService_getInput_presult__isset;

class WateringService_getInput_presult {
 public:

  static const char* ascii_fingerprint; // = "D5AC64616352116A03D8E6BA8250FEF9";
  static const uint8_t binary_fingerprint[16]; // = {0xD5,0xAC,0x64,0x61,0x63,0x52,0x11,0x6A,0x03,0xD8,0xE6,0xBA,0x82,0x50,0xFE,0xF9};


  virtual ~WateringService_getInput_presult() throw();
  HardwareInput* success;
  InvalidOperation ouch;

  _WateringService_getInput_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const WateringService_getInput_presult& obj);
};

typedef struct _WateringService_startPump_args__isset {
  _WateringService_startPump_args__isset() : pumpId(false) {}
  bool pumpId :1;
} _WateringService_startPump_args__isset;

class WateringService_startPump_args {
 public:

  static const char* ascii_fingerprint; // = "E86CACEB22240450EDCBEFC3A83970E4";
  static const uint8_t binary_fingerprint[16]; // = {0xE8,0x6C,0xAC,0xEB,0x22,0x24,0x04,0x50,0xED,0xCB,0xEF,0xC3,0xA8,0x39,0x70,0xE4};

  WateringService_startPump_args(const WateringService_startPump_args&);
  WateringService_startPump_args& operator=(const WateringService_startPump_args&);
  WateringService_startPump_args() : pumpId(0) {
  }

  virtual ~WateringService_startPump_args() throw();
  int32_t pumpId;

  _WateringService_startPump_args__isset __isset;

  void __set_pumpId(const int32_t val);

  bool operator == (const WateringService_startPump_args & rhs) const
  {
    if (!(pumpId == rhs.pumpId))
      return false;
    return true;
  }
  bool operator != (const WateringService_startPump_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const WateringService_startPump_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const WateringService_startPump_args& obj);
};


class WateringService_startPump_pargs {
 public:

  static const char* ascii_fingerprint; // = "E86CACEB22240450EDCBEFC3A83970E4";
  static const uint8_t binary_fingerprint[16]; // = {0xE8,0x6C,0xAC,0xEB,0x22,0x24,0x04,0x50,0xED,0xCB,0xEF,0xC3,0xA8,0x39,0x70,0xE4};


  virtual ~WateringService_startPump_pargs() throw();
  const int32_t* pumpId;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const WateringService_startPump_pargs& obj);
};

typedef struct _WateringService_startPump_result__isset {
  _WateringService_startPump_result__isset() : ouch(false) {}
  bool ouch :1;
} _WateringService_startPump_result__isset;

class WateringService_startPump_result {
 public:

  static const char* ascii_fingerprint; // = "75163450D5D62165E86860A3D30E517A";
  static const uint8_t binary_fingerprint[16]; // = {0x75,0x16,0x34,0x50,0xD5,0xD6,0x21,0x65,0xE8,0x68,0x60,0xA3,0xD3,0x0E,0x51,0x7A};

  WateringService_startPump_result(const WateringService_startPump_result&);
  WateringService_startPump_result& operator=(const WateringService_startPump_result&);
  WateringService_startPump_result() {
  }

  virtual ~WateringService_startPump_result() throw();
  InvalidOperation ouch;

  _WateringService_startPump_result__isset __isset;

  void __set_ouch(const InvalidOperation& val);

  bool operator == (const WateringService_startPump_result & rhs) const
  {
    if (!(ouch == rhs.ouch))
      return false;
    return true;
  }
  bool operator != (const WateringService_startPump_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const WateringService_startPump_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const WateringService_startPump_result& obj);
};

typedef struct _WateringService_startPump_presult__isset {
  _WateringService_startPump_presult__isset() : ouch(false) {}
  bool ouch :1;
} _WateringService_startPump_presult__isset;

class WateringService_startPump_presult {
 public:

  static const char* ascii_fingerprint; // = "75163450D5D62165E86860A3D30E517A";
  static const uint8_t binary_fingerprint[16]; // = {0x75,0x16,0x34,0x50,0xD5,0xD6,0x21,0x65,0xE8,0x68,0x60,0xA3,0xD3,0x0E,0x51,0x7A};


  virtual ~WateringService_startPump_presult() throw();
  InvalidOperation ouch;

  _WateringService_startPump_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const WateringService_startPump_presult& obj);
};

typedef struct _WateringService_stopPump_args__isset {
  _WateringService_stopPump_args__isset() : pumpId(false) {}
  bool pumpId :1;
} _WateringService_stopPump_args__isset;

class WateringService_stopPump_args {
 public:

  static const char* ascii_fingerprint; // = "E86CACEB22240450EDCBEFC3A83970E4";
  static const uint8_t binary_fingerprint[16]; // = {0xE8,0x6C,0xAC,0xEB,0x22,0x24,0x04,0x50,0xED,0xCB,0xEF,0xC3,0xA8,0x39,0x70,0xE4};

  WateringService_stopPump_args(const WateringService_stopPump_args&);
  WateringService_stopPump_args& operator=(const WateringService_stopPump_args&);
  WateringService_stopPump_args() : pumpId(0) {
  }

  virtual ~WateringService_stopPump_args() throw();
  int32_t pumpId;

  _WateringService_stopPump_args__isset __isset;

  void __set_pumpId(const int32_t val);

  bool operator == (const WateringService_stopPump_args & rhs) const
  {
    if (!(pumpId == rhs.pumpId))
      return false;
    return true;
  }
  bool operator != (const WateringService_stopPump_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const WateringService_stopPump_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const WateringService_stopPump_args& obj);
};


class WateringService_stopPump_pargs {
 public:

  static const char* ascii_fingerprint; // = "E86CACEB22240450EDCBEFC3A83970E4";
  static const uint8_t binary_fingerprint[16]; // = {0xE8,0x6C,0xAC,0xEB,0x22,0x24,0x04,0x50,0xED,0xCB,0xEF,0xC3,0xA8,0x39,0x70,0xE4};


  virtual ~WateringService_stopPump_pargs() throw();
  const int32_t* pumpId;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const WateringService_stopPump_pargs& obj);
};

typedef struct _WateringService_stopPump_result__isset {
  _WateringService_stopPump_result__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _WateringService_stopPump_result__isset;

class WateringService_stopPump_result {
 public:

  static const char* ascii_fingerprint; // = "0E3755C4848BC180B5320A302F311F65";
  static const uint8_t binary_fingerprint[16]; // = {0x0E,0x37,0x55,0xC4,0x84,0x8B,0xC1,0x80,0xB5,0x32,0x0A,0x30,0x2F,0x31,0x1F,0x65};

  WateringService_stopPump_result(const WateringService_stopPump_result&);
  WateringService_stopPump_result& operator=(const WateringService_stopPump_result&);
  WateringService_stopPump_result() {
  }

  virtual ~WateringService_stopPump_result() throw();
  StopPumpResult success;
  InvalidOperation ouch;

  _WateringService_stopPump_result__isset __isset;

  void __set_success(const StopPumpResult& val);

  void __set_ouch(const InvalidOperation& val);

  bool operator == (const WateringService_stopPump_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ouch == rhs.ouch))
      return false;
    return true;
  }
  bool operator != (const WateringService_stopPump_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const WateringService_stopPump_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const WateringService_stopPump_result& obj);
};

typedef struct _WateringService_stopPump_presult__isset {
  _WateringService_stopPump_presult__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _WateringService_stopPump_presult__isset;

class WateringService_stopPump_presult {
 public:

  static const char* ascii_fingerprint; // = "0E3755C4848BC180B5320A302F311F65";
  static const uint8_t binary_fingerprint[16]; // = {0x0E,0x37,0x55,0xC4,0x84,0x8B,0xC1,0x80,0xB5,0x32,0x0A,0x30,0x2F,0x31,0x1F,0x65};


  virtual ~WateringService_stopPump_presult() throw();
  StopPumpResult* success;
  InvalidOperation ouch;

  _WateringService_stopPump_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const WateringService_stopPump_presult& obj);
};

class WateringServiceClient : virtual public WateringServiceIf {
 public:
  WateringServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  WateringServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void configure(const Configuration& configuration);
  void send_configure(const Configuration& configuration);
  void recv_configure();
  void pour(const Container::type from, const Container::type to);
  void send_pour(const Container::type from, const Container::type to);
  void recv_pour();
  void getInput(HardwareInput& _return);
  void send_getInput();
  void recv_getInput(HardwareInput& _return);
  void startPump(const int32_t pumpId);
  void send_startPump(const int32_t pumpId);
  void recv_startPump();
  void stopPump(StopPumpResult& _return, const int32_t pumpId);
  void send_stopPump(const int32_t pumpId);
  void recv_stopPump(StopPumpResult& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class WateringServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<WateringServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (WateringServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_configure(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_pour(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getInput(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_startPump(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_stopPump(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  WateringServiceProcessor(boost::shared_ptr<WateringServiceIf> iface) :
    iface_(iface) {
    processMap_["configure"] = &WateringServiceProcessor::process_configure;
    processMap_["pour"] = &WateringServiceProcessor::process_pour;
    processMap_["getInput"] = &WateringServiceProcessor::process_getInput;
    processMap_["startPump"] = &WateringServiceProcessor::process_startPump;
    processMap_["stopPump"] = &WateringServiceProcessor::process_stopPump;
  }

  virtual ~WateringServiceProcessor() {}
};

class WateringServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  WateringServiceProcessorFactory(const ::boost::shared_ptr< WateringServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< WateringServiceIfFactory > handlerFactory_;
};

class WateringServiceMultiface : virtual public WateringServiceIf {
 public:
  WateringServiceMultiface(std::vector<boost::shared_ptr<WateringServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~WateringServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<WateringServiceIf> > ifaces_;
  WateringServiceMultiface() {}
  void add(boost::shared_ptr<WateringServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void configure(const Configuration& configuration) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->configure(configuration);
    }
    ifaces_[i]->configure(configuration);
  }

  void pour(const Container::type from, const Container::type to) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->pour(from, to);
    }
    ifaces_[i]->pour(from, to);
  }

  void getInput(HardwareInput& _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getInput(_return);
    }
    ifaces_[i]->getInput(_return);
    return;
  }

  void startPump(const int32_t pumpId) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->startPump(pumpId);
    }
    ifaces_[i]->startPump(pumpId);
  }

  void stopPump(StopPumpResult& _return, const int32_t pumpId) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->stopPump(_return, pumpId);
    }
    ifaces_[i]->stopPump(_return, pumpId);
    return;
  }

};

} // namespace

#endif
