/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef WateringService_CONSTANTS_H
#define WateringService_CONSTANTS_H

#include "WateringService_types.h"

namespace Tabletochki {

class WateringServiceConstants {
 public:
  WateringServiceConstants();

};

extern const WateringServiceConstants g_WateringService_constants;

} // namespace

#endif
