/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "WateringService_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace Tabletochki {

int _kContainerValues[] = {
  Container::VISIBLE,
  Container::HIDDEN
};
const char* _kContainerNames[] = {
  "VISIBLE",
  "HIDDEN"
};
const std::map<int, const char*> _Container_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(2, _kContainerValues, _kContainerNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

int _kErrorCodeValues[] = {
  ErrorCode::INVALID_CONFIGURATION,
  ErrorCode::DEVICE_ALREADY_IN_USE
};
const char* _kErrorCodeNames[] = {
  "INVALID_CONFIGURATION",
  "DEVICE_ALREADY_IN_USE"
};
const std::map<int, const char*> _ErrorCode_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(2, _kErrorCodeValues, _kErrorCodeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));


InvalidOperation::~InvalidOperation() throw() {
}


void InvalidOperation::__set_what(const ErrorCode::type val) {
  this->what = val;
}

void InvalidOperation::__set_why(const std::string& val) {
  this->why = val;
}

const char* InvalidOperation::ascii_fingerprint = "19B5240589E680301A7E32DF3971EFBE";
const uint8_t InvalidOperation::binary_fingerprint[16] = {0x19,0xB5,0x24,0x05,0x89,0xE6,0x80,0x30,0x1A,0x7E,0x32,0xDF,0x39,0x71,0xEF,0xBE};

uint32_t InvalidOperation::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast0;
          xfer += iprot->readI32(ecast0);
          this->what = (ErrorCode::type)ecast0;
          this->__isset.what = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->why);
          this->__isset.why = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t InvalidOperation::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("InvalidOperation");

  xfer += oprot->writeFieldBegin("what", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32((int32_t)this->what);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("why", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->why);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(InvalidOperation &a, InvalidOperation &b) {
  using ::std::swap;
  swap(a.what, b.what);
  swap(a.why, b.why);
  swap(a.__isset, b.__isset);
}

InvalidOperation::InvalidOperation(const InvalidOperation& other1) : TException() {
  what = other1.what;
  why = other1.why;
  __isset = other1.__isset;
}
InvalidOperation& InvalidOperation::operator=(const InvalidOperation& other2) {
  what = other2.what;
  why = other2.why;
  __isset = other2.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const InvalidOperation& obj) {
  using apache::thrift::to_string;
  out << "InvalidOperation(";
  out << "what=" << to_string(obj.what);
  out << ", " << "why=" << to_string(obj.why);
  out << ")";
  return out;
}


StopPumpResult::~StopPumpResult() throw() {
}


void StopPumpResult::__set_workingTimeSecond(const int32_t val) {
  this->workingTimeSecond = val;
}

const char* StopPumpResult::ascii_fingerprint = "E86CACEB22240450EDCBEFC3A83970E4";
const uint8_t StopPumpResult::binary_fingerprint[16] = {0xE8,0x6C,0xAC,0xEB,0x22,0x24,0x04,0x50,0xED,0xCB,0xEF,0xC3,0xA8,0x39,0x70,0xE4};

uint32_t StopPumpResult::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->workingTimeSecond);
          this->__isset.workingTimeSecond = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t StopPumpResult::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("StopPumpResult");

  xfer += oprot->writeFieldBegin("workingTimeSecond", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->workingTimeSecond);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(StopPumpResult &a, StopPumpResult &b) {
  using ::std::swap;
  swap(a.workingTimeSecond, b.workingTimeSecond);
  swap(a.__isset, b.__isset);
}

StopPumpResult::StopPumpResult(const StopPumpResult& other3) {
  workingTimeSecond = other3.workingTimeSecond;
  __isset = other3.__isset;
}
StopPumpResult& StopPumpResult::operator=(const StopPumpResult& other4) {
  workingTimeSecond = other4.workingTimeSecond;
  __isset = other4.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const StopPumpResult& obj) {
  using apache::thrift::to_string;
  out << "StopPumpResult(";
  out << "workingTimeSecond=" << to_string(obj.workingTimeSecond);
  out << ")";
  return out;
}


HardwareInput::~HardwareInput() throw() {
}


void HardwareInput::__set_buttonPressed(const bool val) {
  this->buttonPressed = val;
}

const char* HardwareInput::ascii_fingerprint = "5892306F7B861249AE8E27C8ED619593";
const uint8_t HardwareInput::binary_fingerprint[16] = {0x58,0x92,0x30,0x6F,0x7B,0x86,0x12,0x49,0xAE,0x8E,0x27,0xC8,0xED,0x61,0x95,0x93};

uint32_t HardwareInput::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->buttonPressed);
          this->__isset.buttonPressed = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t HardwareInput::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("HardwareInput");

  xfer += oprot->writeFieldBegin("buttonPressed", ::apache::thrift::protocol::T_BOOL, 1);
  xfer += oprot->writeBool(this->buttonPressed);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(HardwareInput &a, HardwareInput &b) {
  using ::std::swap;
  swap(a.buttonPressed, b.buttonPressed);
  swap(a.__isset, b.__isset);
}

HardwareInput::HardwareInput(const HardwareInput& other5) {
  buttonPressed = other5.buttonPressed;
  __isset = other5.__isset;
}
HardwareInput& HardwareInput::operator=(const HardwareInput& other6) {
  buttonPressed = other6.buttonPressed;
  __isset = other6.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const HardwareInput& obj) {
  using apache::thrift::to_string;
  out << "HardwareInput(";
  out << "buttonPressed=" << to_string(obj.buttonPressed);
  out << ")";
  return out;
}


PumpConfiguration::~PumpConfiguration() throw() {
}


void PumpConfiguration::__set_productivityMillilitresPerSecond(const int32_t val) {
  this->productivityMillilitresPerSecond = val;
}

const char* PumpConfiguration::ascii_fingerprint = "E86CACEB22240450EDCBEFC3A83970E4";
const uint8_t PumpConfiguration::binary_fingerprint[16] = {0xE8,0x6C,0xAC,0xEB,0x22,0x24,0x04,0x50,0xED,0xCB,0xEF,0xC3,0xA8,0x39,0x70,0xE4};

uint32_t PumpConfiguration::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->productivityMillilitresPerSecond);
          this->__isset.productivityMillilitresPerSecond = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t PumpConfiguration::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("PumpConfiguration");

  xfer += oprot->writeFieldBegin("productivityMillilitresPerSecond", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->productivityMillilitresPerSecond);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(PumpConfiguration &a, PumpConfiguration &b) {
  using ::std::swap;
  swap(a.productivityMillilitresPerSecond, b.productivityMillilitresPerSecond);
  swap(a.__isset, b.__isset);
}

PumpConfiguration::PumpConfiguration(const PumpConfiguration& other7) {
  productivityMillilitresPerSecond = other7.productivityMillilitresPerSecond;
  __isset = other7.__isset;
}
PumpConfiguration& PumpConfiguration::operator=(const PumpConfiguration& other8) {
  productivityMillilitresPerSecond = other8.productivityMillilitresPerSecond;
  __isset = other8.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const PumpConfiguration& obj) {
  using apache::thrift::to_string;
  out << "PumpConfiguration(";
  out << "productivityMillilitresPerSecond=" << to_string(obj.productivityMillilitresPerSecond);
  out << ")";
  return out;
}


Configuration::~Configuration() throw() {
}


void Configuration::__set_pumpsConfiguration(const std::vector<PumpConfiguration> & val) {
  this->pumpsConfiguration = val;
}

const char* Configuration::ascii_fingerprint = "1171AE793D9EC39A88B865BB7391D846";
const uint8_t Configuration::binary_fingerprint[16] = {0x11,0x71,0xAE,0x79,0x3D,0x9E,0xC3,0x9A,0x88,0xB8,0x65,0xBB,0x73,0x91,0xD8,0x46};

uint32_t Configuration::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->pumpsConfiguration.clear();
            uint32_t _size9;
            ::apache::thrift::protocol::TType _etype12;
            xfer += iprot->readListBegin(_etype12, _size9);
            this->pumpsConfiguration.resize(_size9);
            uint32_t _i13;
            for (_i13 = 0; _i13 < _size9; ++_i13)
            {
              xfer += this->pumpsConfiguration[_i13].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.pumpsConfiguration = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t Configuration::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("Configuration");

  xfer += oprot->writeFieldBegin("pumpsConfiguration", ::apache::thrift::protocol::T_LIST, 1);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->pumpsConfiguration.size()));
    std::vector<PumpConfiguration> ::const_iterator _iter14;
    for (_iter14 = this->pumpsConfiguration.begin(); _iter14 != this->pumpsConfiguration.end(); ++_iter14)
    {
      xfer += (*_iter14).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(Configuration &a, Configuration &b) {
  using ::std::swap;
  swap(a.pumpsConfiguration, b.pumpsConfiguration);
  swap(a.__isset, b.__isset);
}

Configuration::Configuration(const Configuration& other15) {
  pumpsConfiguration = other15.pumpsConfiguration;
  __isset = other15.__isset;
}
Configuration& Configuration::operator=(const Configuration& other16) {
  pumpsConfiguration = other16.pumpsConfiguration;
  __isset = other16.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const Configuration& obj) {
  using apache::thrift::to_string;
  out << "Configuration(";
  out << "pumpsConfiguration=" << to_string(obj.pumpsConfiguration);
  out << ")";
  return out;
}

} // namespace
